Repository AY2021S1-CS2103T-F11-2/tp, pull requests merged in 2020-10, with the labels that each got.

#44 Add Delete and Edit Commands for Meeting
  src/main/java/seedu/address/logic/commands/meeting/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/meeting/EditCommand.java
  src/main/java/seedu/address/logic/parser/meeting/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/meeting/EditCommandParser.java
Labels: enhancement

#43 Implement Add and Delete deliverable features
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/deliverable/AddCommand.java
  src/main/java/seedu/address/logic/commands/deliverable/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/deliverable/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/deliverable/CliSyntax.java
  src/main/java/seedu/address/logic/parser/deliverable/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/deliverable/DeliverableBookParser.java
  src/main/java/seedu/address/logic/parser/deliverable/ParserUtil.java
  src/main/java/seedu/address/logic/parser/person/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/person/CliSyntax.java
  src/main/java/seedu/address/model/deliverable/deliverable/Deadline.java
  src/main/java/seedu/address/model/deliverable/deliverable/Deliverable.java
  src/main/java/seedu/address/model/deliverable/deliverable/Description.java
  src/main/java/seedu/address/model/deliverable/deliverable/Title.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/deliverable/JsonAdaptedDeliverable.java
  src/main/java/seedu/address/ui/DeliverableCard.java
  src/main/resources/view/DeliverableListCard.fxml
  src/test/java/seedu/address/model/deliverable/deliverable/DeliverableTest.java
  src/test/java/seedu/address/testutil/DeliverableBookBuilder.java
  src/test/java/seedu/address/testutil/DeliverableBuilder.java
  src/test/java/seedu/address/testutil/DeliverableUtil.java
  src/test/java/seedu/address/testutil/TypicalDeliverables.java
Labels: enhancement

#94 Enable assertions
  build.gradle
Labels: testing

#98 Update DevloperGuide with Switch Mode implementation
  docs/DeveloperGuide.md
  docs/diagrams/SwitchModeSequenceDiagram.puml
  docs/images/SwitchModeSequenceDiagram.png
Labels: documentation

#102 Add ViewCommand implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/ViewCommandSequenceDiagram.png
Labels: documentation

#99 Update User Guide
  docs/UserGuide.md
  docs/images/helpMessage.JPG
  docs/images/helpMessage.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#103 Add DateTime Implementation Docs and update Manual Testing docs
  docs/DeveloperGuide.md
  docs/diagrams/DateTimeClass.puml
  docs/images/DateTimeClass.png
Labels: documentation

#107 Add Overall Completion Percentage feature to DG Implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/OCPSequenceDiagram.puml
  docs/images/OCPSequenceDiagram.png
Labels: documentation

#118 Edit various documentations to fit Productiv
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/index.md
Labels: documentation

#111 Add Meeting Test Cases
  src/test/java/seedu/address/logic/commands/meeting/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/meeting/AddCommandParserTest.java
  src/test/java/seedu/address/model/meeting/meeting/FromToTest.java
  src/test/java/seedu/address/model/meeting/meeting/LocationTest.java
  src/test/java/seedu/address/model/meeting/meeting/MeetingTest.java
  src/test/java/seedu/address/model/meeting/meeting/UniqueMeetingListTest.java
  src/test/java/seedu/address/model/meeting/util/MeetingComparatorTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: testing

#112 Amend deadline to use DateTime util class; Create test cases for Deliverables
  src/main/java/seedu/address/logic/commands/deliverable/AddCommand.java
  src/main/java/seedu/address/logic/commands/deliverable/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/deliverable/EditCommand.java
  src/main/java/seedu/address/logic/commands/meeting/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/meeting/EditCommand.java
  src/main/java/seedu/address/logic/parser/deliverable/AddCommandParser.java
  src/main/java/seedu/address/model/deliverable/DeliverableBook.java
  src/main/java/seedu/address/model/deliverable/ModelDeliverableManager.java
  src/main/java/seedu/address/model/deliverable/deliverable/Deadline.java
  src/main/java/seedu/address/model/meeting/meeting/From.java
  src/main/java/seedu/address/storage/deliverable/JsonAdaptedDeliverable.java
  src/main/java/seedu/address/ui/DeliverableCard.java
  src/main/java/seedu/address/ui/DeliverableDetailsPanel.java
  src/test/java/seedu/address/logic/commands/deliverable/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/deliverable/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverable/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/deliverable/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverable/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverable/EditDeliverableDescriptorTest.java
  src/test/java/seedu/address/logic/commands/meeting/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/meeting/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/person/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/person/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/meeting/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/person/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/person/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/person/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/person/ParserUtilTest.java
  src/test/java/seedu/address/model/deliverable/deliverable/DeliverableTest.java
  src/test/java/seedu/address/testutil/DeliverableBuilder.java
  src/test/java/seedu/address/testutil/DeliverableUtil.java
  src/test/java/seedu/address/testutil/EditDeliverableDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeliverables.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: implementation, testing

#121 Add Meeting find and list command
  src/main/java/seedu/address/logic/commands/meeting/FindCommand.java
  src/main/java/seedu/address/logic/commands/meeting/ListCommand.java
  src/main/java/seedu/address/logic/parser/meeting/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/meeting/MeetingBookParser.java
  src/main/java/seedu/address/model/meeting/meeting/TitleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/meeting/TitleDescriptionContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/meeting/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/meeting/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/meeting/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/meeting/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: implementation

#122 Implement Clear for Meeting
  src/main/java/seedu/address/logic/commands/meeting/ClearCommand.java
  src/main/java/seedu/address/logic/parser/meeting/MeetingBookParser.java
  src/main/java/seedu/address/model/meeting/ModelMeetingManager.java
Labels: enhancement

#123 Implement deliverables autosort & Create more test cases
  src/main/java/seedu/address/model/deliverable/DeliverableBook.java
  src/main/java/seedu/address/model/deliverable/deliverable/UniqueDeliverableList.java
  src/main/java/seedu/address/model/meeting/MeetingBook.java
  src/main/java/seedu/address/model/meeting/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/person/AddressBook.java
  src/main/java/seedu/address/model/person/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/util/PersonComparator.java
  src/main/java/seedu/address/model/util/TimeEventComparator.java
  src/main/java/seedu/address/ui/Calendar.java
  src/test/java/seedu/address/logic/commands/deliverable/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverable/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverable/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverable/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/deliverable/ListCommandTest.java
  src/test/java/seedu/address/model/meeting/util/MeetingComparatorTest.java
  src/test/java/seedu/address/model/util/TimeEventComparatorTest.java
  src/test/java/seedu/address/testutil/DeliverableUtil.java
  src/test/java/seedu/address/testutil/TypicalDeliverables.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: documentation, enhancement

#128 Add glossary and find & list command meeting docs.
  docs/UserGuide.md
Labels: documentation

#129 Implement OCP display; Disallow marking done of completed deliverables
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/deliverable/DoneCommand.java
  src/main/java/seedu/address/model/deliverable/DeliverableBook.java
  src/main/java/seedu/address/model/deliverable/ModelDeliverableManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectCompletionStatusPanel.java
  src/main/resources/view/ProjectCompletionStatusPanel.fxml
Labels: implementation

#126 Update FAQ in UG
  docs/UserGuide.md
Labels: documentation

#130 Include tip box in UG in list command for all modes
  docs/UserGuide.md
Labels: documentation
